import pandas as pd
import os

def generate_raw_data():
    """
    Generates a structured dataset containing Indian EV cars.
    This acts as a reliable data source instead of scraping, which is often blocked.
    """
    
    # List of dictionaries containing car data
    cars = [
        {
            "car_id": "EV001",
            "car_name": "Tata Nexon EV",
            "brand": "Tata",
            "model": "Nexon EV",
            "variant": "Empowered Plus Long Range",
            "price_ex_showroom_lakh": "Rs. 19.49 Lakh",
            "price_on_road_lakh": "Rs. 20.50 Lakh",
            "min_price_lakh": "Rs. 14.49 Lakh",
            "max_price_lakh": "Rs. 19.49 Lakh",
            "battery_capacity_kwh": "40.5 kWh",
            "claimed_range_km": "465 km",
            "real_world_range_km": "330 km",
            "charging_time_ac_hours": "6.0",
            "charging_time_dc_minutes": "56.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "106.4 kW",
            "torque_nm": "215 Nm",
            "top_speed_kmph": "120",
            "acceleration_0_100_sec": "8.9",
            "body_type": "SUV",
            "segment": "Compact SUV",
            "seating_capacity": "5",
            "boot_space_litres": "350",
            "ground_clearance_mm": "205",
            "safety_rating": "5",
            "airbags": "6",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Feature-rich, comfortable ride, 5-star safety rating, good real-world range",
            "cons": "Fit and finish could be better, high speed highway efficiency drops",
            "source_url": "https://www.tatamotors.com/nexon-ev",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV002",
            "car_name": "MG ZS EV",
            "brand": "MG",
            "model": "ZS EV",
            "variant": "Exclusive Pro",
            "price_ex_showroom_lakh": "Rs. 24.98 Lakh",
            "price_on_road_lakh": "Rs. 26.50 Lakh",
            "min_price_lakh": "Rs. 18.98 Lakh",
            "max_price_lakh": "Rs. 24.98 Lakh",
            "battery_capacity_kwh": "50.3 kWh",
            "claimed_range_km": "461 km",
            "real_world_range_km": "340 km",
            "charging_time_ac_hours": "9.0",
            "charging_time_dc_minutes": "60.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "130.0 kW",
            "torque_nm": "280 Nm",
            "top_speed_kmph": "140",
            "acceleration_0_100_sec": "8.5",
            "body_type": "SUV",
            "segment": "Mid-size SUV",
            "seating_capacity": "5",
            "boot_space_litres": "470",
            "ground_clearance_mm": "190",
            "safety_rating": "5",
            "airbags": "6",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "5",
            "battery_warranty_years": "8",
            "battery_warranty_km": "150000",
            "home_charging_supported": "Yes",
            "pros": "Premium interiors, punchy performance, spacious, Level 2 ADAS",
            "cons": "Outdated infotainment system, suspension is slightly bouncy",
            "source_url": "https://www.mgmotor.co.in/vehicles/mgzsev",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV003",
            "car_name": "Tata Punch EV",
            "brand": "Tata",
            "model": "Punch EV",
            "variant": "Empowered Plus S Long Range",
            "price_ex_showroom_lakh": "Rs. 15.49 Lakh",
            "price_on_road_lakh": "Rs. 16.50 Lakh",
            "min_price_lakh": "Rs. 10.99 Lakh",
            "max_price_lakh": "Rs. 15.49 Lakh",
            "battery_capacity_kwh": "35.0 kWh",
            "claimed_range_km": "421 km",
            "real_world_range_km": "300 km",
            "charging_time_ac_hours": "5.0",
            "charging_time_dc_minutes": "56.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "90.0 kW",
            "torque_nm": "190 Nm",
            "top_speed_kmph": "140",
            "acceleration_0_100_sec": "9.5",
            "body_type": "SUV",
            "segment": "Micro SUV",
            "seating_capacity": "5",
            "boot_space_litres": "366",
            "ground_clearance_mm": "190",
            "safety_rating": "5",
            "airbags": "6",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Great features, solid build quality, frunk available, good ground clearance",
            "cons": "Rear seat space is tight, somewhat noisy suspension",
            "source_url": "https://ev.tatamotors.com/punchev.html",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV004",
            "car_name": "Mahindra XUV400 EV",
            "brand": "Mahindra",
            "model": "XUV400",
            "variant": "EL Pro 39.4 kWh",
            "price_ex_showroom_lakh": "Rs. 17.49 Lakh",
            "price_on_road_lakh": "Rs. 18.60 Lakh",
            "min_price_lakh": "Rs. 15.49 Lakh",
            "max_price_lakh": "Rs. 17.49 Lakh",
            "battery_capacity_kwh": "39.4 kWh",
            "claimed_range_km": "456 km",
            "real_world_range_km": "310 km",
            "charging_time_ac_hours": "6.5",
            "charging_time_dc_minutes": "50.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "110.0 kW",
            "torque_nm": "310 Nm",
            "top_speed_kmph": "150",
            "acceleration_0_100_sec": "8.3",
            "body_type": "SUV",
            "segment": "Compact SUV",
            "seating_capacity": "5",
            "boot_space_litres": "378",
            "ground_clearance_mm": "200",
            "safety_rating": "4",
            "airbags": "6",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Fast acceleration, very spacious cabin, comfortable ride",
            "cons": "Lacks some modern features compared to Nexon EV, interior looks dated",
            "source_url": "https://auto.mahindra.com/suv/xuv400",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV005",
            "car_name": "BYD Atto 3",
            "brand": "BYD",
            "model": "Atto 3",
            "variant": "Extended Range",
            "price_ex_showroom_lakh": "Rs. 33.99 Lakh",
            "price_on_road_lakh": "Rs. 35.80 Lakh",
            "min_price_lakh": "Rs. 33.99 Lakh",
            "max_price_lakh": "Rs. 34.49 Lakh",
            "battery_capacity_kwh": "60.48 kWh",
            "claimed_range_km": "521 km",
            "real_world_range_km": "420 km",
            "charging_time_ac_hours": "10.0",
            "charging_time_dc_minutes": "50.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "150.0 kW",
            "torque_nm": "310 Nm",
            "top_speed_kmph": "160",
            "acceleration_0_100_sec": "7.3",
            "body_type": "SUV",
            "segment": "Mid-size SUV",
            "seating_capacity": "5",
            "boot_space_litres": "440",
            "ground_clearance_mm": "175",
            "safety_rating": "5",
            "airbags": "7",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "6",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Exceptional battery tech (Blade Battery), very long range, quirky but premium interiors",
            "cons": "Polarizing interior design, brand network is still growing",
            "source_url": "https://bydautoindia.com/byd-atto3",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV006",
            "car_name": "Tata Tiago EV",
            "brand": "Tata",
            "model": "Tiago EV",
            "variant": "XZ Plus Tech LUX Long Range",
            "price_ex_showroom_lakh": "Rs. 11.49 Lakh",
            "price_on_road_lakh": "Rs. 12.10 Lakh",
            "min_price_lakh": "Rs. 7.99 Lakh",
            "max_price_lakh": "Rs. 11.49 Lakh",
            "battery_capacity_kwh": "24.0 kWh",
            "claimed_range_km": "315 km",
            "real_world_range_km": "220 km",
            "charging_time_ac_hours": "3.6",
            "charging_time_dc_minutes": "58.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "55.0 kW",
            "torque_nm": "114 Nm",
            "top_speed_kmph": "120",
            "acceleration_0_100_sec": "11.5",
            "body_type": "Hatchback",
            "segment": "Entry Hatchback",
            "seating_capacity": "5",
            "boot_space_litres": "240",
            "ground_clearance_mm": "166",
            "safety_rating": "4",
            "airbags": "2",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Very affordable, great for city commutes, easy to drive",
            "cons": "Low highway range, basic features, limited boot space",
            "source_url": "https://ev.tatamotors.com/tiagoev.html",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV007",
            "car_name": "MG Comet EV",
            "brand": "MG",
            "model": "Comet EV",
            "variant": "Exclusive",
            "price_ex_showroom_lakh": "Rs. 9.14 Lakh",
            "price_on_road_lakh": "Rs. 9.50 Lakh",
            "min_price_lakh": "Rs. 6.99 Lakh",
            "max_price_lakh": "Rs. 9.14 Lakh",
            "battery_capacity_kwh": "17.3 kWh",
            "claimed_range_km": "230 km",
            "real_world_range_km": "180 km",
            "charging_time_ac_hours": "7.0",
            "charging_time_dc_minutes": "None",
            "fast_charging_available": "No",
            "motor_power_kw": "31.2 kW",
            "torque_nm": "110 Nm",
            "top_speed_kmph": "100",
            "acceleration_0_100_sec": "15.0",
            "body_type": "Hatchback",
            "segment": "Micro Hatchback",
            "seating_capacity": "4",
            "boot_space_litres": "0",
            "ground_clearance_mm": "165",
            "safety_rating": "0",
            "airbags": "2",
            "transmission": "Automatic",
            "drive_type": "RWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "120000",
            "home_charging_supported": "Yes",
            "pros": "Extremely compact for city traffic, high-quality dual screens, extremely cheap to run",
            "cons": "No fast charging, tiny wheels, basically 0 boot space with rear seats up",
            "source_url": "https://www.mgmotor.co.in/vehicles/mgcometev",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV008",
            "car_name": "Hyundai Ioniq 5",
            "brand": "Hyundai",
            "model": "Ioniq 5",
            "variant": "RWD",
            "price_ex_showroom_lakh": "Rs. 45.95 Lakh",
            "price_on_road_lakh": "Rs. 48.20 Lakh",
            "min_price_lakh": "Rs. 45.95 Lakh",
            "max_price_lakh": "Rs. 45.95 Lakh",
            "battery_capacity_kwh": "72.6 kWh",
            "claimed_range_km": "631 km",
            "real_world_range_km": "480 km",
            "charging_time_ac_hours": "7.0",
            "charging_time_dc_minutes": "18.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "160.0 kW",
            "torque_nm": "350 Nm",
            "top_speed_kmph": "185",
            "acceleration_0_100_sec": "7.6",
            "body_type": "SUV",
            "segment": "Premium SUV",
            "seating_capacity": "5",
            "boot_space_litres": "527",
            "ground_clearance_mm": "163",
            "safety_rating": "5",
            "airbags": "6",
            "transmission": "Automatic",
            "drive_type": "RWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Stunning retro-futuristic design, 800V architecture for ultra-fast charging, extremely spacious",
            "cons": "Expensive, rear visibility is limited, ground clearance is low for an SUV",
            "source_url": "https://www.hyundai.com/in/en/find-a-car/ioniq5/highlights.html",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV009",
            "car_name": "Kia EV6",
            "brand": "Kia",
            "model": "EV6",
            "variant": "GT Line AWD",
            "price_ex_showroom_lakh": "Rs. 65.95 Lakh",
            "price_on_road_lakh": "Rs. 69.50 Lakh",
            "min_price_lakh": "Rs. 60.95 Lakh",
            "max_price_lakh": "Rs. 65.95 Lakh",
            "battery_capacity_kwh": "77.4 kWh",
            "claimed_range_km": "708 km",
            "real_world_range_km": "500 km",
            "charging_time_ac_hours": "7.3",
            "charging_time_dc_minutes": "18.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "239.0 kW",
            "torque_nm": "605 Nm",
            "top_speed_kmph": "192",
            "acceleration_0_100_sec": "5.2",
            "body_type": "Crossover",
            "segment": "Premium Crossover",
            "seating_capacity": "5",
            "boot_space_litres": "490",
            "ground_clearance_mm": "155",
            "safety_rating": "5",
            "airbags": "8",
            "transmission": "Automatic",
            "drive_type": "AWD",
            "warranty_years": "3",
            "battery_warranty_years": "8",
            "battery_warranty_km": "160000",
            "home_charging_supported": "Yes",
            "pros": "Thrilling performance, incredibly fast charging, sporty and sharp design",
            "cons": "Very expensive, low ground clearance, rear headroom is a bit tight",
            "source_url": "https://www.kia.com/in/our-vehicles/ev6/showroom.html",
            "last_updated": "2024-05-01"
        },
        {
            "car_id": "EV010",
            "car_name": "Citroen eC3",
            "brand": "Citroen",
            "model": "eC3",
            "variant": "Shine",
            "price_ex_showroom_lakh": "Rs. 13.50 Lakh",
            "price_on_road_lakh": "Rs. 14.20 Lakh",
            "min_price_lakh": "Rs. 11.61 Lakh",
            "max_price_lakh": "Rs. 13.50 Lakh",
            "battery_capacity_kwh": "29.2 kWh",
            "claimed_range_km": "320 km",
            "real_world_range_km": "240 km",
            "charging_time_ac_hours": "10.5",
            "charging_time_dc_minutes": "57.0",
            "fast_charging_available": "Yes",
            "motor_power_kw": "42.0 kW",
            "torque_nm": "143 Nm",
            "top_speed_kmph": "107",
            "acceleration_0_100_sec": "13.5",
            "body_type": "Hatchback",
            "segment": "Premium Hatchback",
            "seating_capacity": "5",
            "boot_space_litres": "315",
            "ground_clearance_mm": "170",
            "safety_rating": "0",
            "airbags": "2",
            "transmission": "Automatic",
            "drive_type": "FWD",
            "warranty_years": "3",
            "battery_warranty_years": "7",
            "battery_warranty_km": "140000",
            "home_charging_supported": "Yes",
            "pros": "Very comfortable ride quality, spacious interior, good boot space",
            "cons": "Basic interior quality, misses out on many modern features, poor safety rating",
            "source_url": "https://www.citroen.in/models/e-c3",
            "last_updated": "2024-05-01"
        }
    ]

    df = pd.DataFrame(cars)
    
    # Ensure data directory exists
    os.makedirs('data', exist_ok=True)
    
    # Save raw data
    output_path = 'data/raw_ev_data.csv'
    df.to_csv(output_path, index=False)
    print(f"Raw data successfully collected and saved to {output_path}")

if __name__ == '__main__':
    generate_raw_data()
